from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_PUBG(object):
    def setupUi(self, PUBG):
        PUBG.setObjectName("PUBG")
        PUBG.setWindowModality(QtCore.Qt.ApplicationModal)
        PUBG.resize(543, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./_internal/GHUB.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PUBG.setWindowIcon(icon)
        PUBG.setWindowFilePath("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PUBG)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Container = QtWidgets.QWidget(PUBG)
        self.Container.setObjectName("Container")
        self.gridLayout = QtWidgets.QGridLayout(self.Container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleBox = QtWidgets.QWidget(self.Container)
        self.TitleBox.setObjectName("TitleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TitleBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Title = QtWidgets.QLabel(self.TitleBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setTabletTracking(False)
        self.Title.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Title.setTextFormat(QtCore.Qt.RichText)
        self.Title.setScaledContents(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setWordWrap(False)
        self.Title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Title.setObjectName("Title")
        self.verticalLayout_4.addWidget(self.Title)
        self.WinVersion = QtWidgets.QLabel(self.TitleBox)
        self.WinVersion.setText("")
        self.WinVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.WinVersion.setObjectName("WinVersion")
        self.verticalLayout_4.addWidget(self.WinVersion)
        self.gridLayout.addWidget(self.TitleBox, 0, 0, 1, 1)
        self.RemindBox = QtWidgets.QWidget(self.Container)
        self.RemindBox.setObjectName("RemindBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.RemindBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Remind = QtWidgets.QTextEdit(self.RemindBox)
        self.Remind.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.Remind.setUndoRedoEnabled(False)
        self.Remind.setReadOnly(True)
        self.Remind.setObjectName("Remind")
        self.horizontalLayout_2.addWidget(self.Remind)
        self.gridLayout.addWidget(self.RemindBox, 1, 0, 1, 1)
        self.FunctionBox = QtWidgets.QWidget(self.Container)
        self.FunctionBox.setObjectName("FunctionBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.FunctionBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ScopeBox = QtWidgets.QWidget(self.FunctionBox)
        self.ScopeBox.setObjectName("ScopeBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.ScopeBox)
        self.horizontalLayout_15.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ScopeMode = QtWidgets.QGroupBox(self.ScopeBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ScopeMode.setFont(font)
        self.ScopeMode.setObjectName("ScopeMode")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.ScopeMode)
        self.horizontalLayout_16.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.LongPress = QtWidgets.QRadioButton(self.ScopeMode)
        self.LongPress.setObjectName("LongPress")
        self.horizontalLayout_16.addWidget(self.LongPress)
        self.ClickPress = QtWidgets.QRadioButton(self.ScopeMode)
        self.ClickPress.setObjectName("ClickPress")
        self.horizontalLayout_16.addWidget(self.ClickPress)
        self.horizontalLayout_16.setStretch(0, 3)
        self.horizontalLayout_16.setStretch(1, 2)
        self.horizontalLayout_15.addWidget(self.ScopeMode)
        self.IsScope = QtWidgets.QGroupBox(self.ScopeBox)
        self.IsScope.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.IsScope.setFont(font)
        self.IsScope.setObjectName("IsScope")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.IsScope)
        self.horizontalLayout_17.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.OpenScope = QtWidgets.QRadioButton(self.IsScope)
        self.OpenScope.setObjectName("OpenScope")
        self.horizontalLayout_17.addWidget(self.OpenScope)
        self.CloseScope = QtWidgets.QRadioButton(self.IsScope)
        self.CloseScope.setObjectName("CloseScope")
        self.horizontalLayout_17.addWidget(self.CloseScope)
        self.horizontalLayout_15.addWidget(self.IsScope)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.ScopeBox, 2, 0, 1, 1)
        self.IdentifyBox = QtWidgets.QWidget(self.FunctionBox)
        self.IdentifyBox.setObjectName("IdentifyBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.IdentifyBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OneGunsBox = QtWidgets.QGroupBox(self.IdentifyBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OneGunsBox.setFont(font)
        self.OneGunsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.OneGunsBox.setFlat(True)
        self.OneGunsBox.setObjectName("OneGunsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OneGunsBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Name1Box = QtWidgets.QWidget(self.OneGunsBox)
        self.Name1Box.setObjectName("Name1Box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Name1Box)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Name1Lable = QtWidgets.QLabel(self.Name1Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name1Lable.setFont(font)
        self.Name1Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Name1Lable.setObjectName("Name1Lable")
        self.horizontalLayout_5.addWidget(self.Name1Lable)
        self.Name1Name = QtWidgets.QLabel(self.Name1Box)
        self.Name1Name.setStyleSheet("color: rgb(56, 56, 56);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.Name1Name.setText("")
        self.Name1Name.setObjectName("Name1Name")
        self.horizontalLayout_5.addWidget(self.Name1Name)
        self.verticalLayout.addWidget(self.Name1Box)
        self.Muzzle1Box = QtWidgets.QWidget(self.OneGunsBox)
        self.Muzzle1Box.setObjectName("Muzzle1Box")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Muzzle1Box)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Muzzle1Lable = QtWidgets.QLabel(self.Muzzle1Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Muzzle1Lable.setFont(font)
        self.Muzzle1Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Muzzle1Lable.setObjectName("Muzzle1Lable")
        self.horizontalLayout_6.addWidget(self.Muzzle1Lable)
        self.Muzzle1Name = QtWidgets.QLabel(self.Muzzle1Box)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Muzzle1Name.setFont(font)
        self.Muzzle1Name.setStyleSheet("color: rgb(0, 134, 0);\n"
"font: 75 10pt \"Arial\";")
        self.Muzzle1Name.setText("")
        self.Muzzle1Name.setObjectName("Muzzle1Name")
        self.horizontalLayout_6.addWidget(self.Muzzle1Name)
        self.verticalLayout.addWidget(self.Muzzle1Box)
        self.Scope1Box = QtWidgets.QWidget(self.OneGunsBox)
        self.Scope1Box.setObjectName("Scope1Box")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Scope1Box)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Scope1Lable = QtWidgets.QLabel(self.Scope1Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Scope1Lable.setFont(font)
        self.Scope1Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Scope1Lable.setObjectName("Scope1Lable")
        self.horizontalLayout_8.addWidget(self.Scope1Lable)
        self.Scope1Name = QtWidgets.QLabel(self.Scope1Box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Scope1Name.setFont(font)
        self.Scope1Name.setStyleSheet("color: rgb(255, 8, 45);\n"
"font: 75 10pt \"Agency FB\";")
        self.Scope1Name.setText("")
        self.Scope1Name.setObjectName("Scope1Name")
        self.horizontalLayout_8.addWidget(self.Scope1Name)
        self.verticalLayout.addWidget(self.Scope1Box)
        self.Grip1Box = QtWidgets.QWidget(self.OneGunsBox)
        self.Grip1Box.setObjectName("Grip1Box")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Grip1Box)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Grip1Lable = QtWidgets.QLabel(self.Grip1Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Grip1Lable.setFont(font)
        self.Grip1Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Grip1Lable.setObjectName("Grip1Lable")
        self.horizontalLayout_7.addWidget(self.Grip1Lable)
        self.Grip1Name = QtWidgets.QLabel(self.Grip1Box)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Grip1Name.setFont(font)
        self.Grip1Name.setStyleSheet("color: rgb(168, 84, 0);\n"
"font: 75 10pt \"Arial\";")
        self.Grip1Name.setText("")
        self.Grip1Name.setObjectName("Grip1Name")
        self.horizontalLayout_7.addWidget(self.Grip1Name)
        self.verticalLayout.addWidget(self.Grip1Box)
        self.Butt1Box = QtWidgets.QWidget(self.OneGunsBox)
        self.Butt1Box.setObjectName("Butt1Box")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Butt1Box)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Butt1Label = QtWidgets.QLabel(self.Butt1Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Butt1Label.setFont(font)
        self.Butt1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Butt1Label.setObjectName("Butt1Label")
        self.horizontalLayout_9.addWidget(self.Butt1Label)
        self.Butt1Name = QtWidgets.QLabel(self.Butt1Box)
        self.Butt1Name.setStyleSheet("color:rgb(0, 85, 255);\n"
"font: 75 10pt \"Arial\";")
        self.Butt1Name.setText("")
        self.Butt1Name.setObjectName("Butt1Name")
        self.horizontalLayout_9.addWidget(self.Butt1Name)
        self.verticalLayout.addWidget(self.Butt1Box)
        self.horizontalLayout_4.addWidget(self.OneGunsBox)
        self.TwoGunsBox = QtWidgets.QGroupBox(self.IdentifyBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TwoGunsBox.setFont(font)
        self.TwoGunsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TwoGunsBox.setFlat(True)
        self.TwoGunsBox.setObjectName("TwoGunsBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TwoGunsBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name2Box = QtWidgets.QWidget(self.TwoGunsBox)
        self.Name2Box.setObjectName("Name2Box")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Name2Box)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Name2Lable = QtWidgets.QLabel(self.Name2Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name2Lable.setFont(font)
        self.Name2Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Name2Lable.setObjectName("Name2Lable")
        self.horizontalLayout_10.addWidget(self.Name2Lable)
        self.Name2Name = QtWidgets.QLabel(self.Name2Box)
        self.Name2Name.setStyleSheet("color: rgb(56, 56, 56);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.Name2Name.setText("")
        self.Name2Name.setObjectName("Name2Name")
        self.horizontalLayout_10.addWidget(self.Name2Name)
        self.verticalLayout_2.addWidget(self.Name2Box)
        self.Muzzle2Box = QtWidgets.QWidget(self.TwoGunsBox)
        self.Muzzle2Box.setObjectName("Muzzle2Box")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Muzzle2Box)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Muzzle2Lable = QtWidgets.QLabel(self.Muzzle2Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Muzzle2Lable.setFont(font)
        self.Muzzle2Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Muzzle2Lable.setObjectName("Muzzle2Lable")
        self.horizontalLayout_11.addWidget(self.Muzzle2Lable)
        self.Muzzle2Name = QtWidgets.QLabel(self.Muzzle2Box)
        self.Muzzle2Name.setStyleSheet("color: rgb(0, 134, 0);\n"
"font: 75 10pt \"Arial\";")
        self.Muzzle2Name.setText("")
        self.Muzzle2Name.setObjectName("Muzzle2Name")
        self.horizontalLayout_11.addWidget(self.Muzzle2Name)
        self.verticalLayout_2.addWidget(self.Muzzle2Box)
        self.Scope2Box = QtWidgets.QWidget(self.TwoGunsBox)
        self.Scope2Box.setObjectName("Scope2Box")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Scope2Box)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Scope2Lable = QtWidgets.QLabel(self.Scope2Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Scope2Lable.setFont(font)
        self.Scope2Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Scope2Lable.setObjectName("Scope2Lable")
        self.horizontalLayout_12.addWidget(self.Scope2Lable)
        self.Scope2Name = QtWidgets.QLabel(self.Scope2Box)
        self.Scope2Name.setStyleSheet("color: rgb(255, 8, 45);\n"
"font: 75 10pt \"Agency FB\";")
        self.Scope2Name.setText("")
        self.Scope2Name.setObjectName("Scope2Name")
        self.horizontalLayout_12.addWidget(self.Scope2Name)
        self.verticalLayout_2.addWidget(self.Scope2Box)
        self.Grip2Box = QtWidgets.QWidget(self.TwoGunsBox)
        self.Grip2Box.setObjectName("Grip2Box")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.Grip2Box)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Grip2Lable = QtWidgets.QLabel(self.Grip2Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Grip2Lable.setFont(font)
        self.Grip2Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Grip2Lable.setObjectName("Grip2Lable")
        self.horizontalLayout_14.addWidget(self.Grip2Lable)
        self.Grip2Name = QtWidgets.QLabel(self.Grip2Box)
        self.Grip2Name.setStyleSheet("color:rgb(0, 85, 255);\n"
"font: 75 10pt \"Arial\";")
        self.Grip2Name.setText("")
        self.Grip2Name.setObjectName("Grip2Name")
        self.horizontalLayout_14.addWidget(self.Grip2Name)
        self.verticalLayout_2.addWidget(self.Grip2Box)
        self.Butt2Box = QtWidgets.QWidget(self.TwoGunsBox)
        self.Butt2Box.setObjectName("Butt2Box")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Butt2Box)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Butt2Lable = QtWidgets.QLabel(self.Butt2Box)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Butt2Lable.setFont(font)
        self.Butt2Lable.setAlignment(QtCore.Qt.AlignCenter)
        self.Butt2Lable.setObjectName("Butt2Lable")
        self.horizontalLayout_13.addWidget(self.Butt2Lable)
        self.Butt2Name = QtWidgets.QLabel(self.Butt2Box)
        self.Butt2Name.setStyleSheet("color: rgb(168, 84, 0);\n"
"font: 75 10pt \"Arial\";")
        self.Butt2Name.setText("")
        self.Butt2Name.setObjectName("Butt2Name")
        self.horizontalLayout_13.addWidget(self.Butt2Name)
        self.verticalLayout_2.addWidget(self.Butt2Box)
        self.horizontalLayout_4.addWidget(self.TwoGunsBox)
        self.gridLayout_2.addWidget(self.IdentifyBox, 0, 0, 1, 1)
        self.InfoBox = QtWidgets.QWidget(self.FunctionBox)
        self.InfoBox.setObjectName("InfoBox")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.InfoBox)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.InfoBoxs = QtWidgets.QGroupBox(self.InfoBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InfoBoxs.setFont(font)
        self.InfoBoxs.setAlignment(QtCore.Qt.AlignCenter)
        self.InfoBoxs.setObjectName("InfoBoxs")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.InfoBoxs)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Info = QtWidgets.QTextEdit(self.InfoBoxs)
        self.Info.setReadOnly(True)
        self.Info.setObjectName("Info")
        self.horizontalLayout_22.addWidget(self.Info)
        self.horizontalLayout_21.addWidget(self.InfoBoxs)
        self.gridLayout_2.addWidget(self.InfoBox, 3, 0, 1, 1)
        self.ParameterBox = QtWidgets.QWidget(self.FunctionBox)
        self.ParameterBox.setObjectName("ParameterBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.ParameterBox)
        self.horizontalLayout_18.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.EquipBox = QtWidgets.QGroupBox(self.ParameterBox)
        self.EquipBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.EquipBox.setFont(font)
        self.EquipBox.setFlat(False)
        self.EquipBox.setObjectName("EquipBox")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.EquipBox)
        self.horizontalLayout_20.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.OneGuns = QtWidgets.QRadioButton(self.EquipBox)
        self.OneGuns.setStyleSheet("color: rgb(255, 0, 0);")
        self.OneGuns.setObjectName("OneGuns")
        self.horizontalLayout_20.addWidget(self.OneGuns)
        self.TwoGuns = QtWidgets.QRadioButton(self.EquipBox)
        self.TwoGuns.setStyleSheet("color: rgb(255, 0, 0);")
        self.TwoGuns.setObjectName("TwoGuns")
        self.horizontalLayout_20.addWidget(self.TwoGuns)
        self.Orders = QtWidgets.QRadioButton(self.EquipBox)
        self.Orders.setObjectName("Orders")
        self.horizontalLayout_20.addWidget(self.Orders)
        self.horizontalLayout_18.addWidget(self.EquipBox)
        self.PoseBox = QtWidgets.QGroupBox(self.ParameterBox)
        self.PoseBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PoseBox.setFont(font)
        self.PoseBox.setObjectName("PoseBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.PoseBox)
        self.horizontalLayout_19.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.SquatDown = QtWidgets.QRadioButton(self.PoseBox)
        self.SquatDown.setObjectName("SquatDown")
        self.horizontalLayout_19.addWidget(self.SquatDown)
        self.GetDown = QtWidgets.QRadioButton(self.PoseBox)
        self.GetDown.setObjectName("GetDown")
        self.horizontalLayout_19.addWidget(self.GetDown)
        self.Stand = QtWidgets.QRadioButton(self.PoseBox)
        self.Stand.setCheckable(True)
        self.Stand.setChecked(False)
        self.Stand.setAutoRepeat(False)
        self.Stand.setObjectName("Stand")
        self.horizontalLayout_19.addWidget(self.Stand)
        self.horizontalLayout_18.addWidget(self.PoseBox)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.ParameterBox, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 2)
        self.gridLayout.addWidget(self.FunctionBox, 2, 0, 1, 1)
        self.ResolutionBox = QtWidgets.QWidget(self.Container)
        self.ResolutionBox.setObjectName("ResolutionBox")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.ResolutionBox)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Resolution = QtWidgets.QGroupBox(self.ResolutionBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Resolution.setFont(font)
        self.Resolution.setAlignment(QtCore.Qt.AlignCenter)
        self.Resolution.setFlat(True)
        self.Resolution.setCheckable(False)
        self.Resolution.setObjectName("Resolution")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.Resolution)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ResolutionLabel = QtWidgets.QLabel(self.Resolution)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.horizontalLayout_24.addWidget(self.ResolutionLabel)
        self.ResolutionSelect = QtWidgets.QComboBox(self.Resolution)
        self.ResolutionSelect.setObjectName("ResolutionSelect")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.setItemText(0, "1920x1080")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.addItem("")
        self.ResolutionSelect.addItem("")
        self.horizontalLayout_24.addWidget(self.ResolutionSelect)
        self.ResolutionBtn = QtWidgets.QPushButton(self.Resolution)
        self.ResolutionBtn.setObjectName("ResolutionBtn")
        self.horizontalLayout_24.addWidget(self.ResolutionBtn)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 2)
        self.horizontalLayout_24.setStretch(2, 1)
        self.horizontalLayout_23.addWidget(self.Resolution)
        self.Sensitivity = QtWidgets.QGroupBox(self.ResolutionBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Sensitivity.setFont(font)
        self.Sensitivity.setAlignment(QtCore.Qt.AlignCenter)
        self.Sensitivity.setFlat(True)
        self.Sensitivity.setObjectName("Sensitivity")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.Sensitivity)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.SensitivityLabel = QtWidgets.QLabel(self.Sensitivity)
        self.SensitivityLabel.setObjectName("SensitivityLabel")
        self.horizontalLayout_25.addWidget(self.SensitivityLabel)
        self.SensitivitySelect = QtWidgets.QComboBox(self.Sensitivity)
        self.SensitivitySelect.setObjectName("SensitivitySelect")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.SensitivitySelect.addItem("")
        self.horizontalLayout_25.addWidget(self.SensitivitySelect)
        self.SensitivityText = QtWidgets.QLineEdit(self.Sensitivity)
        self.SensitivityText.setObjectName("SensitivityText")
        self.horizontalLayout_25.addWidget(self.SensitivityText)
        self.SensitivityBtn = QtWidgets.QPushButton(self.Sensitivity)
        self.SensitivityBtn.setObjectName("SensitivityBtn")
        self.horizontalLayout_25.addWidget(self.SensitivityBtn)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_25.setStretch(2, 1)
        self.horizontalLayout_25.setStretch(3, 1)
        self.horizontalLayout_23.addWidget(self.Sensitivity)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.gridLayout.addWidget(self.ResolutionBox, 5, 0, 1, 1)
        self.BtnBox = QtWidgets.QWidget(self.Container)
        self.BtnBox.setObjectName("BtnBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.BtnBox)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StatusInfo = QtWidgets.QLineEdit(self.BtnBox)
        self.StatusInfo.setStyleSheet("color: rgb(170, 0, 0);")
        self.StatusInfo.setDragEnabled(False)
        self.StatusInfo.setReadOnly(True)
        self.StatusInfo.setObjectName("StatusInfo")
        self.horizontalLayout_3.addWidget(self.StatusInfo)
        self.Startbtn = QtWidgets.QPushButton(self.BtnBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Startbtn.setFont(font)
        self.Startbtn.setObjectName("Startbtn")
        self.horizontalLayout_3.addWidget(self.Startbtn)
        self.Pausebtn = QtWidgets.QPushButton(self.BtnBox)
        self.Pausebtn.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pausebtn.setFont(font)
        self.Pausebtn.setObjectName("Pausebtn")
        self.horizontalLayout_3.addWidget(self.Pausebtn)
        self.Stopbtn = QtWidgets.QPushButton(self.BtnBox)
        self.Stopbtn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Stopbtn.setFont(font)
        self.Stopbtn.setObjectName("Stopbtn")
        self.horizontalLayout_3.addWidget(self.Stopbtn)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 2)
        self.gridLayout.addWidget(self.BtnBox, 6, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 6)
        self.gridLayout.setRowStretch(5, 1)
        self.verticalLayout_3.addWidget(self.Container)
        self.retranslateUi(PUBG)
        QtCore.QMetaObject.connectSlotsByName(PUBG)

    def retranslateUi(self, PUBG):
        _translate = QtCore.QCoreApplication.translate
        PUBG.setWindowTitle(_translate("PUBG", "LGHUB"))
        self.Title.setText(_translate("PUBG", "PUBG 自动识别鼠标宏"))
        self.Remind.setHtml(_translate("PUBG", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\">使用须知</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\"> 1.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">本软件免费学习使用，禁止倒卖，交流QQ群：695919722</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\"> 2.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">如果觉得好用，可以在下方支持下作者，广告联系作者微信：js_python98</span></p>\n"                                              
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\"> 3.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">使用需要安装罗技GHUB 21版本或LGS蓝驱的驱动，并禁止驱动更新</span></p>\n"                                               
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\"> 4.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">GHUB和本软件都需要以管理员身份运行</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\"> 5.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">分辨率支持：1080p 1.5k 1440p 1660p 2.5k 4k</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\"> </span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\">6.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">打开背包后，按下tab识别，识别率高达95%，支持全配件识别</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\"> </span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\">7.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">适配所有灵敏度</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\"> </span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; font-weight:600; color:#aa0000;\">8.</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\">按下“Home键”弹出隐藏窗口，按下“ins”键重置当前所有状态（枪械，开镜方式，姿态，开镜状态）</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'宋体\',\'monospace\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'宋体\',\'monospace\'; font-size:12pt; color:#ecc48d;\"><br /></p></body></html>"))
        self.ScopeMode.setTitle(_translate("PUBG", "开镜模式"))
        self.LongPress.setText(_translate("PUBG", "长按"))
        self.ClickPress.setText(_translate("PUBG", "单击"))
        self.IsScope.setTitle(_translate("PUBG", "是否开镜"))
        self.OpenScope.setText(_translate("PUBG", "开镜"))
        self.CloseScope.setText(_translate("PUBG", "未开镜"))
        self.OneGunsBox.setTitle(_translate("PUBG", "一号枪"))
        self.Name1Lable.setText(_translate("PUBG", "名称："))
        self.Muzzle1Lable.setText(_translate("PUBG", "枪口："))
        self.Scope1Lable.setText(_translate("PUBG", "倍镜："))
        self.Grip1Lable.setText(_translate("PUBG", "握把："))
        self.Butt1Label.setText(_translate("PUBG", "枪托："))
        self.TwoGunsBox.setTitle(_translate("PUBG", "二号枪"))
        self.Name2Lable.setText(_translate("PUBG", "名称："))
        self.Muzzle2Lable.setText(_translate("PUBG", "枪口："))
        self.Scope2Lable.setText(_translate("PUBG", "倍镜："))
        self.Grip2Lable.setText(_translate("PUBG", "握把："))
        self.Butt2Lable.setText(_translate("PUBG", "枪托："))
        self.InfoBoxs.setTitle(_translate("PUBG", "日志输出"))
        self.EquipBox.setTitle(_translate("PUBG", "当前装备"))
        self.OneGuns.setText(_translate("PUBG", "1号枪"))
        self.TwoGuns.setText(_translate("PUBG", "2号枪"))
        self.Orders.setText(_translate("PUBG", "其他"))
        self.PoseBox.setTitle(_translate("PUBG", "当前姿势"))
        self.SquatDown.setText(_translate("PUBG", "下蹲"))
        self.GetDown.setText(_translate("PUBG", "趴下"))
        self.Stand.setText(_translate("PUBG", "站立"))
        self.Resolution.setTitle(_translate("PUBG", "分辨率设置"))
        self.ResolutionLabel.setText(_translate("PUBG", "当前分辨率："))
        self.ResolutionSelect.setItemText(1, _translate("PUBG", "1728x1080"))
        self.ResolutionSelect.setItemText(2, _translate("PUBG", "2560x1080"))
        self.ResolutionSelect.setItemText(3, _translate("PUBG", "2560x1440"))
        self.ResolutionSelect.setItemText(4, _translate("PUBG", "2560x1600"))
        self.ResolutionSelect.setItemText(5, _translate("PUBG", "3440x1440"))
        self.ResolutionSelect.setItemText(6, _translate("PUBG", "3840x2160"))
        self.ResolutionBtn.setText(_translate("PUBG", "保存设置"))
        self.Sensitivity.setTitle(_translate("PUBG", "灵敏度设置"))
        self.SensitivityLabel.setText(_translate("PUBG", "当前灵敏度："))
        self.SensitivitySelect.setItemText(0, _translate("PUBG", "无"))
        self.SensitivitySelect.setItemText(1, _translate("PUBG", "红点"))
        self.SensitivitySelect.setItemText(2, _translate("PUBG", "全息"))
        self.SensitivitySelect.setItemText(3, _translate("PUBG", "2倍"))
        self.SensitivitySelect.setItemText(4, _translate("PUBG", "3倍"))
        self.SensitivitySelect.setItemText(5, _translate("PUBG", "4倍"))
        self.SensitivitySelect.setItemText(6, _translate("PUBG", "6倍"))
        self.SensitivitySelect.setItemText(7, _translate("PUBG", "8倍"))
        self.SensitivitySelect.setItemText(8, _translate("PUBG", "15倍"))
        self.SensitivitySelect.setItemText(9, _translate("PUBG", "shift"))
        self.SensitivityBtn.setText(_translate("PUBG", "保存设置"))
        self.StatusInfo.setText(_translate("PUBG", "未启动..."))
        self.Startbtn.setText(_translate("PUBG", "启动"))
        self.Pausebtn.setText(_translate("PUBG", "暂停"))
        self.Stopbtn.setText(_translate("PUBG", "退出"))
